### Data Description and Preparation

The electricity consumption data is originally provided at a 30-minute resolution for each French region. To combine it with the weather dataset, which is only available at a daily frequency, we aggregate electricity consumption to the daily level.

For each region and each day, all 30-minute consumption values are summed to obtain the total daily electricity demand. The resulting daily dataset is then merged with the daily weather data using the common date and region identifiers.

This ensures both datasets are aligned at the same temporal resolution before descriptive analysis and modeling.

In [1]:
pip install -q cartiflette

Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
# ele = pd.read_csv("/home/onyxia/work/Python_Project_2A/data/RTE/data_ele-2020-2024.csv")
# climate = pd.read_csv("/home/onyxia/work/Python_Project_2A/data/weather/Region_France_weather_daily_2020_2024.csv")

df = pd.read_csv("/home/onyxia/work/Python_Project_2A/data/temp_electricity.csv")
df["Datetime"] = pd.to_datetime(df["Datetime"])

In [4]:
# ele

In [5]:
# climate

1. **Does electricity consumption vary systematically with temperature?**

In [6]:
df

,Datetime,Consommation,Regions,Nature,year,month,day,ALLSKY_SFC_SW_DWN,CLRSKY_SFC_SW_DWN,GWETROOT,...,QV2M,RH2M,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,WD10M,WS10M,WS2M,insee_dep
0,2020-01-01,403787.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,1,5.39,6.80,0.68,...,4.17,96.11,0.81,5.26,-1.36,6.62,314.6,1.44,0.82,83
1,2020-01-02,443531.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,2,4.78,6.45,0.68,...,4.41,92.78,2.44,8.35,-0.89,9.24,200.2,3.64,2.26,83
2,2020-01-03,434626.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,3,3.80,6.38,0.68,...,5.00,93.72,3.94,8.16,1.49,6.67,246.6,3.21,1.91,83
3,2020-01-04,395169.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,4,3.91,6.99,0.68,...,4.76,94.68,3.18,5.62,-0.64,6.26,335.6,4.34,2.77,83
4,2020-01-05,400169.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,5,5.85,7.13,0.67,...,3.96,93.92,0.77,4.06,-1.25,5.31,354.9,3.75,2.43,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21919,2024-12-27,181429.0,Pays-de-la-Loire,Données consolidées,2024,12,27,2.05,5.86,0.55,...,3.91,94.54,1.20,5.31,-3.47,8.78,115.8,1.72,0.97,52
21920,2024-12-28,171307.0,Pays-de-la-Loire,Données consolidées,2024,12,28,2.10,5.59,0.55,...,4.93,98.06,4.17,5.52,3.20,2.32,188.7,1.12,0.68,52
21921,2024-12-29,169980.0,Pays-de-la-Loire,Données consolidées,2024,12,29,2.32,5.64,0.55,...,4.17,93.09,2.60,4.63,0.94,3.69,72.1,1.22,0.80,52
21922,2024-12-30,185431.0,Pays-de-la-Loire,Données consolidées,2024,12,30,2.34,5.69,0.55,...,3.90,95.37,1.30,2.89,-0.17,3.06,172.1,1.81,1.14,52
21923,2024-12-31,176371.0,Pays-de-la-Loire,Données consolidées,2024,12,31,2.07,5.83,0.55,...,4.30,96.15,2.41,6.71,0.63,6.08,202.0,4.33,2.93,52

In [7]:
df.describe()

,Datetime,Consommation,year,month,day,ALLSKY_SFC_SW_DWN,CLRSKY_SFC_SW_DWN,GWETROOT,GWETTOP,PRECTOTCORR,...,QV2M,RH2M,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,WD10M,WS10M,WS2M,insee_dep
count,21924,21924.000000,21924.00000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,...,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000,21924.000000
mean,2022-07-02 00:00:00,204433.967843,2022.00000,6.521073,15.735085,12.832862,17.736459,0.575099,0.596883,1.994065,...,7.198033,79.303629,12.013618,16.923766,7.537540,9.386226,195.470799,4.279693,2.812103,49.833333
min,2020-01-01 00:00:00,58376.000000,2020.00000,1.000000,1.000000,0.460000,3.730000,0.220000,0.100000,0.000000,...,1.700000,23.680000,-8.040000,-3.690000,-12.570000,0.680000,0.000000,0.620000,0.400000,11.000000
25%,2021-04-01 00:00:00,125892.500000,2021.00000,4.000000,8.000000,5.710000,9.320000,0.480000,0.500000,0.030000,...,5.320000,71.980000,6.827500,10.920000,3.100000,6.700000,114.200000,2.820000,1.770000,27.750000
50%,2022-07-02 00:00:00,191000.500000,2022.00000,7.000000,16.000000,11.700000,17.800000,0.570000,0.610000,0.360000,...,6.990000,81.770000,11.635000,16.440000,7.570000,9.100000,213.300000,3.890000,2.530000,48.000000
75%,2023-10-02 00:00:00,262712.500000,2023.00000,10.000000,23.000000,19.062500,26.110000,0.660000,0.700000,2.350000,...,8.940000,89.630000,17.380000,22.710000,12.170000,11.930000,274.300000,5.340000,3.560000,75.250000
max,2024-12-31 00:00:00,624804.000000,2024.00000,12.000000,31.000000,32.360000,32.990000,0.960000,0.940000,53.790000,...,16.360000,100.000000,33.310000,42.330000,24.850000,21.630000,360.000000,15.030000,10.600000,93.000000
std,NaN,94293.008281,1.41502,3.449291,8.802592,7.962586,8.521331,0.129210,0.138613,3.699876,...,2.469397,13.039571,6.930725,7.922475,6.030541,3.566004,100.094157,1.967521,1.393298,25.531065

In [8]:
df_total = df.groupby("Datetime", as_index=False)["Consommation"].sum()

fig = px.line(df_total, x="Datetime", y="Consommation",
              title="Total Electricity Consumption in France Over Time"
              ,labels={"Consommation": "Consommation (MWh)"})
fig.show()

**Observation :**

In [9]:
from cartiflette import carti_download
import geopandas as gpd
import matplotlib.pyplot as plt
import json

In [10]:
france = carti_download(
      values = ["France"],
      crs = 4326,
      borders = "REGION",
      vectorfile_format="geojson",
      simplification=50,
      filter_by="FRANCE_ENTIERE",
      source="EXPRESS-COG-CARTO-TERRITOIRE",
      year=2022)
france = france.loc[(france["INSEE_REG"] > 10) & (france["INSEE_REG"] != 94)]

france

,INSEE_REG,PAYS,LIBELLE_REGION,POPULATION,SOURCE,geometry
4,84,France,Auvergne-Rhône-Alpes,8042936,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"POLYGON ((6.06386 46.41639, 6.06267 46.4168, 6..."
5,76,France,Occitanie,5933185,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"MULTIPOLYGON (((2.06288 44.97662, 2.06244 44.9..."
6,53,France,Bretagne,3354854,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"MULTIPOLYGON (((-3.97907 47.70396, -3.97953 47..."
7,75,France,Nouvelle-Aquitaine,6010289,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"MULTIPOLYGON (((-0.31325 42.8494, -0.31227 42...."
8,28,France,Normandie,3325032,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"MULTIPOLYGON (((-1.924 49.66512, -1.92439 49.6..."
9,93,France,Provence-Alpes-Côte d'Azur,5081101,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"MULTIPOLYGON (((4.23021 43.46049, 4.2329 43.46..."
10,52,France,Pays de la Loire,3806461,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"MULTIPOLYGON (((-1.10454 46.31496, -1.10269 46..."
11,44,France,Grand Est,5556219,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"POLYGON ((3.41474 48.39019, 3.41443 48.38781, ..."
12,27,France,Bourgogne-Franche-Comté,2805580,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"POLYGON ((7.13026 47.50295, 7.13157 47.50344, ..."
13,11,France,Île-de-France,12262544,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"POLYGON ((1.5014 48.94103, 1.51182 48.93499, 1..."
14,24,France,Centre-Val de Loire,2573180,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"POLYGON ((2.93662 48.16346, 2.90001 48.15965, ..."
15,32,France,Hauts-de-France,6004947,IGN:EXPRESS-COG-CARTO-TERRITOIRE,"POLYGON ((4.23316 49.95775, 4.23239 49.95796, ..."

In [11]:
france.columns

Index(['INSEE_REG', 'PAYS', 'LIBELLE_REGION', 'POPULATION', 'SOURCE',
       'geometry'],
      dtype='object')

In [12]:
# Now i have 2 data which is the my df data and the other one is the regions_gdf. So in order to plot the map of the consumption each region using my data, i need to make sure if the region of my data match with the regions_gdf.

In [13]:
df["Regions"].nunique()
# df["Regions"].unique()

12

In [14]:
# sorted(df["Regions"].unique())
# sorted(france["LIBELLE_REGION"].unique())

In [15]:
#check if the region match to the regions_gdf data. It does exist but just different spelling so need to correct the spelling in df data

set(df["Regions"].unique()) - set(france["LIBELLE_REGION"].unique())

{'Grand-Est', 'Ile-de-France', 'PACA', 'Pays-de-la-Loire'}

In [16]:
#correct spelling

region_mapping = {
    "Grand-Est": "Grand Est",
    "Ile-de-France": "Île-de-France",
    "Pays-de-la-Loire": "Pays de la Loire",
    "PACA": "Provence-Alpes-Côte d'Azur"
}

df["Regions_clean"] = df["Regions"].replace(region_mapping)

In [17]:
set(france["LIBELLE_REGION"].unique()) - set(df["Regions_clean"].unique())

set()

In [18]:
france_geojson = json.loads(france.to_json())
france_geojson

{'type': 'FeatureCollection',
 'features': [{'id': '4',
   'type': 'Feature',
   'properties': {'INSEE_REG': 84,
    'PAYS': 'France',
    'LIBELLE_REGION': 'Auvergne-Rhône-Alpes',
    'POPULATION': 8042936,
    'SOURCE': 'IGN:EXPRESS-COG-CARTO-TERRITOIRE'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[6.063857350782006, 46.416389647447375],
      [6.0626684922207925, 46.41679733645055],
      [6.060147193152213, 46.41791119839804],
      [6.059644440229763, 46.41744977945653],
      [6.0585931776113595, 46.41724456631177],
      [6.057640555619242, 46.41668345495181],
      [6.0570186773400065, 46.416560440061],
      [6.05564508429009, 46.415647431628756],
      [6.0545916377043, 46.41463392238324],
      [6.054329634336186, 46.414166036966435],
      [6.053227050250644, 46.413134907753395],
      [6.053009458788276, 46.41192329552913],
      [6.052056354930915, 46.41125762235352],
      [6.051680771258537, 46.410644983513684],
      [6.051907693090389, 46.40971705259307],
      [6.050524134551334, 46.40801486076804],
      [6.049937009674248, 46.40757908834675],
      [6.049078257481705, 46.406641431422294],
      [6.049240143001619, 46.40620456030363],
      [6.048560628663676, 46.40591002540215],
      [6.047740934313128, 46.40513442117099],
      [6.046526392263974, 46.404332409504505],
      [6.0453290243956666, 46.40313703316441],
      [6.044470455397508, 46.40271388711749],
      [6.044167067866618, 46.40220202915632],
      [6.044449962277203, 46.401902512996756],
      [6.04328662653802, 46.400124077383836],
      [6.042284380292437, 46.3995055989049],
      [6.0420211178161125, 46.398731337503804],
      [6.0413471430883305, 46.39848707855635],
      [6.0405527975247235, 46.39797568459179],
      [6.040509492112167, 46.3975722305681],
      [6.039241398719176, 46.39671570504807],
      [6.0390969687731575, 46.39639064000051],
      [6.037898764670073, 46.39582961197813],
      [6.037347084940286, 46.395394638516585],
      [6.037269036456499, 46.394810981592016],
      [6.0367622870161295, 46.394317136914175],
      [6.036965936295052, 46.39338895698103],
      [6.036530971349918, 46.39259312373003],
      [6.03585984388713, 46.39171886869016],
      [6.0352517028592905, 46.39162601648221],
      [6.034609113129226, 46.39093662825024],
      [6.033046668736379, 46.390379836722275],
      [6.032650250939553, 46.38947933554434],
      [6.031682815423977, 46.3890598965605],
      [6.030966521737305, 46.388495903336555],
      [6.030020416279477, 46.38813175414128],
      [6.028710424245796, 46.38705275401918],
      [6.028741489580419, 46.38618053805902],
      [6.027468695393102, 46.38565382994065],
      [6.025942460995274, 46.3843597645153],
      [6.0251305259832355, 46.384300202810536],
      [6.024688428410677, 46.383888399160355],
      [6.0232627621865245, 46.383538717005884],
      [6.022867063503277, 46.383682572673486],
      [6.021938929823735, 46.38359362796438],
      [6.021070136310726, 46.38321204040947],
      [6.020723621117568, 46.38287969271475],
      [6.0199205702476375, 46.38262701862233],
      [6.0194946320976515, 46.382200350246315],
      [6.019587383893032, 46.381381475343645],
      [6.018618293111277, 46.381280973490526],
      [6.017317674401151, 46.38055304214339],
      [6.017228766696904, 46.380098524631826],
      [6.0176756913233564, 46.379703721215186],
      [6.017158645967183, 46.37939479977247],
      [6.016661161495828, 46.379510689128075],
      [6.016487545484782, 46.378936760256984],
      [6.017087213406836, 46.37887944449395],
      [6.0172488669562, 46.37845884808034],
      [6.016401511859696, 46.37829833696647],
      [6.015711352705246, 46.3777777188261],
      [6.015625285819842, 46.37739791850195],
      [6.015014957716391, 46.377120290945086],
      [6.014725308408664, 46.37642507274837],
      [6.013514399632828, 46.37609302650955],
      [6.012728265927069, 46.37623905527973],
      [6.011112586358527, 46.375295002312754],
      [6.009631088082927, 46.37482407948768],
      [6.00725519925542, 46.37380902376391],
      [6.0060777529108895, 46.372994820615624],
      [6.006110941312107, 46.37217843200316],
      [6.0056446591251005, 46.371724845253546],
      [6.0050540975764966, 46.37170977310555],
      [6.003246087094234, 46.37112212045372],
      [6.0026728282763555, 46.371445401050266],
      [6.001871213506754, 46.37081139526978],
      [6.000598249990684, 46.370341177505125],
      [6.000022144823429, 46.3698778437937],
      [5.998557537026744, 46.36925945669082],
      [5.996985237513749, 46.36826721570296],
      [5.996564802757652, 46.36817283588795],
      [5.994953122685889, 46.367387057959334],
      [5.994371157032031, 46.36724284647697],
      [5.994035132800896, 46.36674073872821],
      [5.993410020737306, 46.36680671436612],
      [5.993006756445898, 46.36638386517083],
      [5.991112312995167, 46.36561446953692],
      [5.991047293490298, 46.365282763047475],
      [5.989698986512237, 46.364906319410906],
      [5.9883483709221155, 46.364677703396815],
      [5.987505171624275, 46.3648493869446],
      [5.986757542693235, 46.36519788181244],
      [5.985835215207968, 46.364850782793965],
      [5.985400376925413, 46.36415840182102],
      [5.984656352828914, 46.36390574691972],
      [5.984070687532701, 46.363883231415144],
      [5.983738490818619, 46.36347290931766],
      [5.983394932014201, 46.36240146796111],
      [5.98340922929091, 46.361614423510034],
      [5.98282832214901, 46.36129711437036],
      [5.983267941270383, 46.36069538278119],
      [5.9823670360342245, 46.35954660958453],
      [5.981725672705663, 46.359027226024146],
      [5.981740322791281, 46.35841318616253],
      [5.981389532960556, 46.35830521679861],
      [5.98170929705905, 46.357534513186366],
      [5.98163572618457, 46.35702100194416],
      [5.980704587251548, 46.35650919271934],
      [5.980425439847904, 46.35520897988206],
      [5.979802154257792, 46.35418449232245],
      [5.9791568610460875, 46.35392561993214],
      [5.978218982237558, 46.35300216098653],
      [5.97790065367431, 46.35219947891126],
      [5.9774808451045764, 46.35185090326403],
      [5.976843998131907, 46.35167470017885],
      [5.975497595487954, 46.350823165011754],
      [5.9735833271360095, 46.3485266356147],
      [5.973460422428136, 46.34796574808374],
      [5.972774101906128, 46.347620504921636],
      [5.972665342101604, 46.34645820838485],
      [5.971649438893134, 46.34579445283131],
      [5.97050573205358, 46.34601079789742],
      [5.970295619484698, 46.34556842364268],
      [5.969782775173388, 46.34537363275281],
      [5.96933812912725, 46.34478147668668],
      [5.968472771195277, 46.343989419237225],
      [5.968341641291743, 46.34370718383216],
      [5.9676520565051865, 46.34344399763275],
      [5.9667510975489995, 46.34254652468505],
      [5.966505746669908, 46.34178967450356],
      [5.965931926221288, 46.34109363745593],
      [5.9656145763053345, 46.34042426466386],
      [5.9658163651466305, 46.33970713911385],
      [5.965292438305292, 46.338275399286985],
      [5.964631986044206, 46.33761224871623],
      [5.962724786837819, 46.337301409686006],
      [5.961812811254122, 46.33614917549161],
      [5.961598109582877, 46.33511578186797],
      [5.960765432704837, 46.334513856664145],
      [5.959993022549774, 46.33456816650734],
      [5.958900032906202, 46.333025929940966],
      [5.958485483554067, 46.33168774168978],
      [5.958204885299636, 46.33138234414604],
      [5.958284259309367, 46.330613443720004],
      [5.957859048076303, 46.330087425266875],
      [5.957629637740153, 46.32945359691247],
      [5.9556825341777, 46.329048167126054],
      [5.954713850100256, 46.32775588043472],
      [5.953811720690945, 46.32702054459635],
      [5.953337751440795, 46.326409269195466],
      [5.95312180746013, 46.325204686292075],
      [5.95258093353775, 46.32475103319775],
      [5.952390559382727, 46.324091854586605],
      [5.951142175934236, 46.32291582282958],
      [5.950299716420038, 46.321283221232555],
      [5.950435981096881, 46.32019296327531],
      [5.950078252991844, 46.31992649085497],
      [5.94880120450907, 46.31937384000212],
      [5.948291620345819, 46.318558017127124],
      [5.947663364156848, 46.318121923437644],
      [5.948051033287686, 46.31764151629848],
      [5.948198520510125, 46.31692763137267],
      [5.94788305972334, 46.316455508844534],
      [5.947279386545102, 46.3161854811128],
      [5.94707866834513, 46.315525661952464],
      [5.946455891062961, 46.314635266075484],
      [5.945538507978591, 46.31414176161675],
      [5.945889788489237, 46.31315498271865],
      [5.9451583082750705, 46.312853107441796],
      [5.944089643315563, 46.31295462556446],
      [5.943470580697569, 46.31266335042619],
      [5.943628263724265, 46.31221052766697],
      [5.943164542480704, 46.31173681857461],
      [5.942094142595155, 46.31163651707333],
      [5.941058830404472, 46.31027826669485],
      [5.941406981247941, 46.3094015175475],
      [5.94139969758238, 46.30875832084392],
      [5.937395807802794, 46.30981862171924],
      [5.9372943278033405, 46.30962389858837],
      [5.9356780616227995, 46.30969710878335],
      [5.935104687483956, 46.310134500640714],
      [5.935379252925588, 46.310550038904616],
      [5.934237535376133, 46.31101018207706],
      [5.932088669273291, 46.3116764640175],
      [5.926039046786288, 46.313809035832556],
      [5.925451025914225, 46.31305100306079],
      [5.923819814164518, 46.31182505211269],
      [5.923472130505911, 46.31166997814924],
      [5.921766694396514, 46.312436414151655],
      [5.9210123911005255, 46.31153394578793],
      [5.920504069094584, 46.31061074838583],
      [5.919636047144773, 46.31006171181376],
      [5.9190133832663925, 46.309309943411435],
      [5.918065387652755, 46.30908913970224],
      [5.917321462622719, 46.308379216464566],
      [5.9171974170621695, 46.30763809427418],
      [5.920160834480773, 46.306861101770465],
      [5.9190657012328565, 46.304954536076494],
      [5.91708090129985, 46.30108925801462],
      [5.916402189070975, 46.29857638270723],
      [5.916255515149819, 46.297580830757084],
      [5.915518952254747, 46.295029785018734],
      [5.914525063151149, 46.294186579561725],
      [5.914917618474099, 46.29399090620321],
      [5.916527506219934, 46.29375774853053],
      [5.916188556741346, 46.29291039461083],
      [5.913344580410229, 46.28922836152279],
      [5.912561345901786, 46.28840858609558],
      [5.91212651417964, 46.28766279470806],
      [5.911527834693362, 46.28725729836442],
      [5.909131502744077, 46.28384306102026],
      [5.9079683779043926, 46.28435846426744],
      [5.902004877382305, 46.28596679260331],
      [5.901003005920296, 46.28616713708706],
      [5.900488819348656, 46.285465678640925],
      [5.899891282641915, 46.285006029696824],
      [5.898272953511987, 46.28539505953093],
      [5.897342291685141, 46.28576206135015],
      [5.89461880672657, 46.28663600714681],
      [5.892704748149896, 46.28502216279681],
      [5.8924369407555135, 46.28467664470665],
      [5.891782445355737, 46.283334442101264],
      [5.890539132144828, 46.28167018501372],
      [5.890263465097071, 46.281495166207065],
      [5.888754279794788, 46.279224006473164],
      [5.887902819799324, 46.27833281759178],
      [5.88677274196253, 46.277529786430826],
      [5.886188868779471, 46.27670929221282],
      [5.884976701797302, 46.275777669643475],
      [5.883131896090231, 46.27415831978228],
      [5.881985412478555, 46.27281861803736],
      [5.880309487358144, 46.271441845386924],
      [5.880080661289519, 46.270846617661775],
      [5.879561056782501, 46.27040472132047],
      [5.879421670043709, 46.270002763257494],
      [5.8786627679302805, 46.26935876838456],
      [5.877975624844167, 46.26901661699715],
      [5.877301809524148, 46.26895255722184],
      [5.877099813880912, 46.26861976031477],
      [5.87620663682464, 46.26808997688507],
      [5.875673636316277, 46.267589832777126],
      [5.874751955037797, 46.26802581034027],
      [5.873081800977825, 46.26695065312633],
      [5.8726683526639105, 46.26640062179963],
      [5.871908407771959, 46.26598187978551],
      [5.869492899680652, 46.26486240485616],
      [5.869210604394355, 46.265276807524096],
      [5.868935062784861, 46.26629115361726],
      [5.868600727471397, 46.267026747066275],
      [5.867849736527748, 46.26799360200263],
      [5.866604887095737, 46.26918193995133],
      [5.865831621848107, 46.26965014731325],
      [5.865805467742078, 46.27011846182527],
      [5.864011538596142, 46.271393579669216],
      [5.863533541705873, 46.27129747834464],
      [5.8619398524936495, 46.26976880135701],
      [5.860763973092056, 46.26882430826835],
      [5.852895361042216, 46.26141952634446],
      [5.850824536098881, 46.26156873892748],
      [5.849570594302993, 46.26206239232045],
      [5.8474951824329855, 46.262099025319415],
      [5.84597660094135, 46.26230100756775],
      [5.8456502980775635, 46.262796643010226],
      [5.845163904494216, 46.263036773749484],
      [5.843753787872161, 46.26297650757102],
      [5.842891620799285, 46.262685380578475],
      [5.842403131108701, 46.26271019775605],
      [5.841667472305798, 46.262403286955966],
      [5.8404745279999295, 46.262371797735774],
      [5.82909801605208, 46.26179378326586],
      [5.826245698352315, 46.26180428791414],
      [5.821660460894082, 46.26221992644265],
      [5.8182001078332055, 46.2629868697179],
      [5.814943201086344, 46.26346754532279],
      [5.804759203835921, 46.26471014782974],
      [5.8034149047279575, 46.26476759907503],
      [5.798780739661031, 46.26527541735154],
      [5.797161293181281, 46.265338659486],
      [5.795532189981119, 46.26554357942495],
      [5.7937533038864055, 46.26563952249846],
      [5.787944911104546, 46.266154990671076],
      [5.7864910284434625, 46.2662554719508],
      [5.777802188852791, 46.26618225035247],
      [5.7766439542215995, 46.26627178479201],
      [5.775079494583954, 46.26652348820935],
      [5.774262000319702, 46.266953389338454],
      [5.7727171203034, 46.26697662078425],
      [5.771909977100233, 46.26730353443243],
      [5.7705809003516935, 46.267329589729265],
      [5.768555513478061, 46.26807627583365],
      [5.767990333437643, 46.26820445379281],
      [5.765579082201773, 46.2680783600355],
      [5.764274677020724, 46.26746130725078],
      [5.762685380354903, 46.267531433422725],
      [5.76206398875058, 46.26729242530876],
      [5.761298419349286, 46.26728577344773],
      [5.760073789222076, 46.266755039341604],
      [5.758743218414914, 46.26654492355449],
      [5.758017898701004, 46.266692250994936],
      [5.756664614909969, 46.266495275939704],
      [5.754534140662436, 46.266421617174586],
      [5.753456073207533, 46.26655582770668],
      [5.751347937721568, 46.26591842826235],
      [5.750111791553885, 46.266060933784104],
      [5.748737867527782, 46.266021142502694],
      [5.745832251995388, 46.26634446999779],
      [5.744267519840681, 46.26682641480512],
      [5.743929292346821, 46.266843580070464],
      [5.738275890938772, 46.26514256128838],
      [5.733356564746289, 46.263774137237284],
      [5.731834981864955, 46.26332502398671],
      [5.730964210626094, 46.26290082084884],
      [5.72899028106383, 46.26142905890472],
      [5.728390535301645, 46.261176738764185],
      [5.725178302665053, 46.260686969644446],
      [5.720939864476016, 46.26351575781877],
      [5.719455517244283, 46.26436304965712],
      [5.7200807507241445, 46.264945479159564],
      [5.720244105122749, 46.26682108738288],
      [5.720183932119815, 46.268015466275244],
      [5.72064059556936, 46.269152441116056],
      [5.720254436469054, 46.27024468808041],
      [5.719823539634579, 46.270567636909284],
      [5.719863342037417, 46.271264069199745],
      [5.71956676080944, 46.27191087444914],
      [5.718608919416631, 46.27287351131743],
      [5.71604919562426, 46.279915646522134],
      [5.714487057662283, 46.28090797615674],
      [5.714442974032477, 46.281224380490045],
      [5.714997496254208, 46.28179320907984],
      [5.715650170389559, 46.28289939857177],
      [5.715790894875213, 46.284111503341585],
      [5.716300086354735, 46.284996761095755],
      [5.716496393195176, 46.28607148666762],
      [5.71692475235036, 46.28668926889997],
      [5.717695187361557, 46.28864679544351],
      [5.718312491417031, 46.28916906099301],
      [5.718376843092866, 46.290202784906924],
      [5.718754121099652, 46.29104703325535],
      [5.7192939761880845, 46.29346236332591],
      [5.7190649135820095, 46.29499954984904],
      [5.718759916788353, 46.29555825012769],
      [5.718719320384761, 46.29780183152339],
      [5.718395985880025, 46.29992782252025],
      [5.7181732014297655, 46.300519696983635],
      [5.716700696802486, 46.30191445489081],
      [5.714595090198946, 46.30902225056107],
      [5.713449246814988, 46.30932886576016],
      [5.711009655906691, 46.30947705846015],
      [5.710163487977958, 46.309429620027494],
      [5.707988746771357, 46.31017421711386],
      [5.702068902341524, 46.31009405987401],
      [5.694604509730142, 46.31022584024374],
      [5.693495389485686, 46.31043587693367],
      [5.692554880958877, 46.30960757157115],
      [5.692197390416539, 46.309450238265825],
      [5.688167230642337, 46.31014548794107],
      [5.68452816694892, 46.31099625782929],
      [5.6842624441036245, 46.312152188917274],
      [5.683331933720386, 46.31497079762414],
      [5.683346601904374, 46.31627689280245],
      [5.683706374283587, 46.316851360495086],
      [5.680794703336359, 46.31881019953568],
      [5.680296710749516, 46.31867865945667],
      [5.679283878938149, 46.31889439574175],
      [5.678016379069849, 46.318875545068906],
      [5.676857807261986, 46.318691041522364],
      [5.6765939830268435, 46.318933299961216],
      [5.675837520405983, 46.318860971520486],
      [5.674997267242064, 46.319042882830864],
      [5.6745150798007895, 46.319553352371614],
      [5.673571854198602, 46.32007644218142],
      [5.672495137033884, 46.321593742996384],
      [5.670000392095618, 46.32328843072621],
      [5.669381724285519, 46.323802074662574],
      [5.667951596106311, 46.32447707552387],
      [5.666451654017493, 46.32478789110517],
      [5.666054193710769, 46.32466474740148],
      [5.664754658959701, 46.32465820864835],
      [5.6641047126831205, 46.32482477361224],
      [5.662749735134987, 46.32472130097894],
      [5.66209143350603, 46.32490336630717],
      [5.661189164559935, 46.324615406758284],
      [5.659787740136028, 46.324439103370906],
      [5.655853938168511, 46.323720887136375],
      [5.652724036200459, 46.32324600809991],
      [5.650368974694069, 46.32330171874925],
      [5.647885965819075, 46.323535144261626],
      [5.645670642094575, 46.32449028987524],
      [5.643976885051082, 46.3249909084719],
      [5.643734956398193, 46.32517851981523],
      [5.6437234895066215, 46.326528449835195],
      [5.646305730873504, 46.32707936788047],
      [5.647787052563618, 46.32874419948019],
      [5.649419392321208, 46.33081274479794],
      [5.649321534355074, 46.331638514731964],
      [5.649901069675903, 46.33414958187911],
      [5.649805729122704, 46.33612764496859],
      [5.649570535513694, 46.33672325436368],
      [5.649117726762167, 46.33728427891976],
      [5.649071339426612, 46.338206156778305],
      [5.649754486918149, 46.34030396967008],
      [5.649709188894975, 46.340711363915396],
      [5.648646448502051, 46.34173344926166],
      [5.647748199174083, 46.342096692110275],
      [5.646330831261949, 46.34305040912571],
      [5.645544620360222, 46.343471397649566],
      [5.644031568459408, 46.34457326312885],
      [5.643367138893513, 46.344849957424586],
      [5.642502993483717, 46.34444023050722],
      [5.642627737403849, 46.34397964305973],
      [5.641958404192052, 46.34202833235824],
      [5.641389305209849, 46.34123515083403],

In [19]:
# print("Number of features:", len(france_geojson["features"]))
# print([f["properties"]["LIBELLE_REGION"] for f in france_geojson["features"]])

In [20]:
df

,Datetime,Consommation,Regions,Nature,year,month,day,ALLSKY_SFC_SW_DWN,CLRSKY_SFC_SW_DWN,GWETROOT,...,RH2M,T2M,T2M_MAX,T2M_MIN,T2M_RANGE,WD10M,WS10M,WS2M,insee_dep,Regions_clean
0,2020-01-01,403787.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,1,5.39,6.80,0.68,...,96.11,0.81,5.26,-1.36,6.62,314.6,1.44,0.82,83,Auvergne-Rhône-Alpes
1,2020-01-02,443531.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,2,4.78,6.45,0.68,...,92.78,2.44,8.35,-0.89,9.24,200.2,3.64,2.26,83,Auvergne-Rhône-Alpes
2,2020-01-03,434626.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,3,3.80,6.38,0.68,...,93.72,3.94,8.16,1.49,6.67,246.6,3.21,1.91,83,Auvergne-Rhône-Alpes
3,2020-01-04,395169.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,4,3.91,6.99,0.68,...,94.68,3.18,5.62,-0.64,6.26,335.6,4.34,2.77,83,Auvergne-Rhône-Alpes
4,2020-01-05,400169.0,Auvergne-Rhône-Alpes,Données définitives,2020,1,5,5.85,7.13,0.67,...,93.92,0.77,4.06,-1.25,5.31,354.9,3.75,2.43,83,Auvergne-Rhône-Alpes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21919,2024-12-27,181429.0,Pays-de-la-Loire,Données consolidées,2024,12,27,2.05,5.86,0.55,...,94.54,1.20,5.31,-3.47,8.78,115.8,1.72,0.97,52,Pays de la Loire
21920,2024-12-28,171307.0,Pays-de-la-Loire,Données consolidées,2024,12,28,2.10,5.59,0.55,...,98.06,4.17,5.52,3.20,2.32,188.7,1.12,0.68,52,Pays de la Loire
21921,2024-12-29,169980.0,Pays-de-la-Loire,Données consolidées,2024,12,29,2.32,5.64,0.55,...,93.09,2.60,4.63,0.94,3.69,72.1,1.22,0.80,52,Pays de la Loire
21922,2024-12-30,185431.0,Pays-de-la-Loire,Données consolidées,2024,12,30,2.34,5.69,0.55,...,95.37,1.30,2.89,-0.17,3.06,172.1,1.81,1.14,52,Pays de la Loire
21923,2024-12-31,176371.0,Pays-de-la-Loire,Données consolidées,2024,12,31,2.07,5.83,0.55,...,96.15,2.41,6.71,0.63,6.08,202.0,4.33,2.93,52,Pays de la Loire

In [21]:
# Daily consumption per region (from cleaned names)
df_day_region = (
    df.groupby(["Datetime", "Regions_clean"], as_index=False)["Consommation"]
      .sum()
)

# Create Month as a period
df_day_region["Month"] = df_day_region["Datetime"].dt.to_period("M")

# Monthly consumption per region
df_month_region = (
    df_day_region
    .groupby(["Month", "Regions_clean"], as_index=False)["Consommation"]
    .sum()
)

# Convert Month back to timestamp and make labels
df_month_region["Month"] = df_month_region["Month"].dt.to_timestamp()
df_month_region["year"] = df_month_region["Month"].dt.year
df_month_region["month_str"] = df_month_region["Month"].dt.strftime("%Y-%m")

df_month_region

         Month               Regions_clean  Consommation  year month_str
0   2020-01-01        Auvergne-Rhône-Alpes    13645505.0  2020   2020-01
1   2020-01-01     Bourgogne-Franche-Comté     4388881.0  2020   2020-01
2   2020-01-01                    Bretagne     4910735.0  2020   2020-01
3   2020-01-01         Centre-Val de Loire     4094049.0  2020   2020-01
4   2020-01-01                   Grand Est     9123842.0  2020   2020-01
..         ...                         ...           ...   ...       ...
715 2024-12-01          Nouvelle-Aquitaine     8678148.0  2024   2024-12
716 2024-12-01                   Occitanie     7804218.0  2024   2024-12
717 2024-12-01            Pays de la Loire     5323098.0  2024   2024-12
718 2024-12-01  Provence-Alpes-Côte d'Azur     7969958.0  2024   2024-12
719 2024-12-01               Île-de-France    14045733.0  2024   2024-12

[720 rows x 5 columns]

In [22]:
year_to_plot = 2022   # <- change this to 2020, 2021, 2023, etc.

df_month_year = df_month_region[df_month_region["year"] == year_to_plot]

# fig = px.choropleth_mapbox(
#     df_month_year,
#     geojson=france_geojson,
#     locations="Regions_clean",                 # column in df_month_year
#     featureidkey="properties.LIBELLE_REGION",  # property in geojson
#     color="Consommation",
#     animation_frame="month_str",               # monthly slider
#     mapbox_style="carto-positron",
#     center={"lat": 46.5, "lon": 2.5},
#     zoom=4.5,
#     opacity=0.7,
#     color_continuous_scale="Viridis",
#     labels={
#         "Consommation": "Consumption (MWh)",
#         "month_str": "Month"
#     },
#     title=f"Monthly Electricity Consumption by Region in France – {year_to_plot}"
# )

# # Add borders so regions are visually clear
# fig.update_traces(marker_line_width=0.5, marker_line_color="black")

# fig.update_layout(
#     margin={"r":0, "t":40, "l":0, "b":0}
# )

# fig.show()